### ISSUE TITLE
PKCS7 not initialized

### ISSUE THREAD

**Issue by steveworkman** [lacostej/apple-dev#1]
Hi Jerome,

I'm having problems running the new code on my build server. Using ruby 1.8.7 I get this error message when it tries to verify the provisioning profiles.

Any ideas?

/private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:284:in `verify': PKCS7 wasn't initialized. (RuntimeError)
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:284:in `initialize'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:244:in `new'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:244:in `pp_uuid'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:252:in `download_profiles'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:248:in `each'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:248:in `download_profiles'
        from /private/var/root/.jenkins/jobs/iOS Enterprise Provisioning Profiles/workspace/lib/apple-dev.rb:236:in `fetch_site_data'
        from ./bin/apple_dev_center.rb:94:in `dumpSite'
        from ./bin/apple_dev_center.rb:109:in `main'
        from ./bin/apple_dev_center.rb:113

**Comment by lacostej** [comment]
Not reproducible
