### ISSUE TITLE
Use new password manager

### ISSUE THREAD

**Issue by KrauseFx** [lacostej/apple-dev#13]
From the README:

> Extract out the password storage functionality into an reusable encrypted password store for use by ruby scripts (in CI environments).

You could use the [fastlane credential manager](https://github.com/fastlane/CredentialsManager) which uses the Mac OS X Keychain to store and retrieve passwords. It supports multiple Apple IDs.

**Comment by lacostej** [comment]
yup, and use spaceship as well.

**Comment by lacostej** [comment]
won't do ! ;)

**Comment by KrauseFx** [comment]
:cry:
