### ISSUE TITLE
-n option broken

### ISSUE THREAD

**Issue by danielkleinert** [lacostej/apple-dev#2]
apple-dev / bin / apple_dev_center.rb: 50

opts.on( '-n', '--name', 'Use the profile name instead of its UUID as basename when saving them') do
      options[:profileFileName] = :name

apple-dev / lib / apple-dev.rb: 254

if profileFileName == :uuid
    basename = p.uuid
else
    basename = p.name
end

It seams to me, that profileFileName will only ever get the value :name and never :uuid.

**Comment by lacostej** [comment]
closed long ago
